// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rmtxcbl.proto

#ifndef PROTOBUF_rmtxcbl_2eproto__INCLUDED
#define PROTOBUF_rmtxcbl_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace rmtxcbl {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_rmtxcbl_2eproto();
void protobuf_AssignDesc_rmtxcbl_2eproto();
void protobuf_ShutdownFile_rmtxcbl_2eproto();

class executable;
class stream;

// ===================================================================

class executable : public ::google::protobuf::Message {
 public:
  executable();
  virtual ~executable();

  executable(const executable& from);

  inline executable& operator=(const executable& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const executable& default_instance();

  void Swap(executable* other);

  // implements Message ----------------------------------------------

  executable* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const executable& from);
  void MergeFrom(const executable& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes exec = 1;
  inline bool has_exec() const;
  inline void clear_exec();
  static const int kExecFieldNumber = 1;
  inline const ::std::string& exec() const;
  inline void set_exec(const ::std::string& value);
  inline void set_exec(const char* value);
  inline void set_exec(const void* value, size_t size);
  inline ::std::string* mutable_exec();
  inline ::std::string* release_exec();
  inline void set_allocated_exec(::std::string* exec);

  // optional string label = 2;
  inline bool has_label() const;
  inline void clear_label();
  static const int kLabelFieldNumber = 2;
  inline const ::std::string& label() const;
  inline void set_label(const ::std::string& value);
  inline void set_label(const char* value);
  inline void set_label(const char* value, size_t size);
  inline ::std::string* mutable_label();
  inline ::std::string* release_label();
  inline void set_allocated_label(::std::string* label);

  // @@protoc_insertion_point(class_scope:rmtxcbl.executable)
 private:
  inline void set_has_exec();
  inline void clear_has_exec();
  inline void set_has_label();
  inline void clear_has_label();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* exec_;
  ::std::string* label_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_rmtxcbl_2eproto();
  friend void protobuf_AssignDesc_rmtxcbl_2eproto();
  friend void protobuf_ShutdownFile_rmtxcbl_2eproto();

  void InitAsDefaultInstance();
  static executable* default_instance_;
};
// -------------------------------------------------------------------

class stream : public ::google::protobuf::Message {
 public:
  stream();
  virtual ~stream();

  stream(const stream& from);

  inline stream& operator=(const stream& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const stream& default_instance();

  void Swap(stream* other);

  // implements Message ----------------------------------------------

  stream* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const stream& from);
  void MergeFrom(const stream& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string out = 1;
  inline bool has_out() const;
  inline void clear_out();
  static const int kOutFieldNumber = 1;
  inline const ::std::string& out() const;
  inline void set_out(const ::std::string& value);
  inline void set_out(const char* value);
  inline void set_out(const char* value, size_t size);
  inline ::std::string* mutable_out();
  inline ::std::string* release_out();
  inline void set_allocated_out(::std::string* out);

  // optional string err = 2;
  inline bool has_err() const;
  inline void clear_err();
  static const int kErrFieldNumber = 2;
  inline const ::std::string& err() const;
  inline void set_err(const ::std::string& value);
  inline void set_err(const char* value);
  inline void set_err(const char* value, size_t size);
  inline ::std::string* mutable_err();
  inline ::std::string* release_err();
  inline void set_allocated_err(::std::string* err);

  // @@protoc_insertion_point(class_scope:rmtxcbl.stream)
 private:
  inline void set_has_out();
  inline void clear_has_out();
  inline void set_has_err();
  inline void clear_has_err();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* out_;
  ::std::string* err_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_rmtxcbl_2eproto();
  friend void protobuf_AssignDesc_rmtxcbl_2eproto();
  friend void protobuf_ShutdownFile_rmtxcbl_2eproto();

  void InitAsDefaultInstance();
  static stream* default_instance_;
};
// ===================================================================


// ===================================================================

// executable

// required bytes exec = 1;
inline bool executable::has_exec() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void executable::set_has_exec() {
  _has_bits_[0] |= 0x00000001u;
}
inline void executable::clear_has_exec() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void executable::clear_exec() {
  if (exec_ != &::google::protobuf::internal::kEmptyString) {
    exec_->clear();
  }
  clear_has_exec();
}
inline const ::std::string& executable::exec() const {
  return *exec_;
}
inline void executable::set_exec(const ::std::string& value) {
  set_has_exec();
  if (exec_ == &::google::protobuf::internal::kEmptyString) {
    exec_ = new ::std::string;
  }
  exec_->assign(value);
}
inline void executable::set_exec(const char* value) {
  set_has_exec();
  if (exec_ == &::google::protobuf::internal::kEmptyString) {
    exec_ = new ::std::string;
  }
  exec_->assign(value);
}
inline void executable::set_exec(const void* value, size_t size) {
  set_has_exec();
  if (exec_ == &::google::protobuf::internal::kEmptyString) {
    exec_ = new ::std::string;
  }
  exec_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* executable::mutable_exec() {
  set_has_exec();
  if (exec_ == &::google::protobuf::internal::kEmptyString) {
    exec_ = new ::std::string;
  }
  return exec_;
}
inline ::std::string* executable::release_exec() {
  clear_has_exec();
  if (exec_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = exec_;
    exec_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void executable::set_allocated_exec(::std::string* exec) {
  if (exec_ != &::google::protobuf::internal::kEmptyString) {
    delete exec_;
  }
  if (exec) {
    set_has_exec();
    exec_ = exec;
  } else {
    clear_has_exec();
    exec_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string label = 2;
inline bool executable::has_label() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void executable::set_has_label() {
  _has_bits_[0] |= 0x00000002u;
}
inline void executable::clear_has_label() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void executable::clear_label() {
  if (label_ != &::google::protobuf::internal::kEmptyString) {
    label_->clear();
  }
  clear_has_label();
}
inline const ::std::string& executable::label() const {
  return *label_;
}
inline void executable::set_label(const ::std::string& value) {
  set_has_label();
  if (label_ == &::google::protobuf::internal::kEmptyString) {
    label_ = new ::std::string;
  }
  label_->assign(value);
}
inline void executable::set_label(const char* value) {
  set_has_label();
  if (label_ == &::google::protobuf::internal::kEmptyString) {
    label_ = new ::std::string;
  }
  label_->assign(value);
}
inline void executable::set_label(const char* value, size_t size) {
  set_has_label();
  if (label_ == &::google::protobuf::internal::kEmptyString) {
    label_ = new ::std::string;
  }
  label_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* executable::mutable_label() {
  set_has_label();
  if (label_ == &::google::protobuf::internal::kEmptyString) {
    label_ = new ::std::string;
  }
  return label_;
}
inline ::std::string* executable::release_label() {
  clear_has_label();
  if (label_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = label_;
    label_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void executable::set_allocated_label(::std::string* label) {
  if (label_ != &::google::protobuf::internal::kEmptyString) {
    delete label_;
  }
  if (label) {
    set_has_label();
    label_ = label;
  } else {
    clear_has_label();
    label_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// stream

// optional string out = 1;
inline bool stream::has_out() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void stream::set_has_out() {
  _has_bits_[0] |= 0x00000001u;
}
inline void stream::clear_has_out() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void stream::clear_out() {
  if (out_ != &::google::protobuf::internal::kEmptyString) {
    out_->clear();
  }
  clear_has_out();
}
inline const ::std::string& stream::out() const {
  return *out_;
}
inline void stream::set_out(const ::std::string& value) {
  set_has_out();
  if (out_ == &::google::protobuf::internal::kEmptyString) {
    out_ = new ::std::string;
  }
  out_->assign(value);
}
inline void stream::set_out(const char* value) {
  set_has_out();
  if (out_ == &::google::protobuf::internal::kEmptyString) {
    out_ = new ::std::string;
  }
  out_->assign(value);
}
inline void stream::set_out(const char* value, size_t size) {
  set_has_out();
  if (out_ == &::google::protobuf::internal::kEmptyString) {
    out_ = new ::std::string;
  }
  out_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* stream::mutable_out() {
  set_has_out();
  if (out_ == &::google::protobuf::internal::kEmptyString) {
    out_ = new ::std::string;
  }
  return out_;
}
inline ::std::string* stream::release_out() {
  clear_has_out();
  if (out_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = out_;
    out_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void stream::set_allocated_out(::std::string* out) {
  if (out_ != &::google::protobuf::internal::kEmptyString) {
    delete out_;
  }
  if (out) {
    set_has_out();
    out_ = out;
  } else {
    clear_has_out();
    out_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string err = 2;
inline bool stream::has_err() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void stream::set_has_err() {
  _has_bits_[0] |= 0x00000002u;
}
inline void stream::clear_has_err() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void stream::clear_err() {
  if (err_ != &::google::protobuf::internal::kEmptyString) {
    err_->clear();
  }
  clear_has_err();
}
inline const ::std::string& stream::err() const {
  return *err_;
}
inline void stream::set_err(const ::std::string& value) {
  set_has_err();
  if (err_ == &::google::protobuf::internal::kEmptyString) {
    err_ = new ::std::string;
  }
  err_->assign(value);
}
inline void stream::set_err(const char* value) {
  set_has_err();
  if (err_ == &::google::protobuf::internal::kEmptyString) {
    err_ = new ::std::string;
  }
  err_->assign(value);
}
inline void stream::set_err(const char* value, size_t size) {
  set_has_err();
  if (err_ == &::google::protobuf::internal::kEmptyString) {
    err_ = new ::std::string;
  }
  err_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* stream::mutable_err() {
  set_has_err();
  if (err_ == &::google::protobuf::internal::kEmptyString) {
    err_ = new ::std::string;
  }
  return err_;
}
inline ::std::string* stream::release_err() {
  clear_has_err();
  if (err_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = err_;
    err_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void stream::set_allocated_err(::std::string* err) {
  if (err_ != &::google::protobuf::internal::kEmptyString) {
    delete err_;
  }
  if (err) {
    set_has_err();
    err_ = err;
  } else {
    clear_has_err();
    err_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace rmtxcbl

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_rmtxcbl_2eproto__INCLUDED
